# Site-specific deployment configuration lives in this file
production:
  repository: git://github.com/uruguay-pais/api-parlamento.git
  branch: master
  server: api.parlamento.datauy.org
  user: deploy
  deploy_to: /var/www/apps/api_parlamento
  rails_env: production
staging:
  repository: git://github.com/uruguay-pais/api-parlamento.git
  branch: master
  server: test.api.parlamento.datauy.org
  user: deploy
  deploy_to: /var/www/apps/api_parlamento
  rails_env: production